require "rake/clean"

require_relative "../lib/dxjruby/version"

CLEAN.include "target/"

task :default => :make_jar

SRC_FILES = Dir.glob("src/**/*").to_a
SRC_FILES << "pom.xml"

ARTIFACT_ID = "dxjruby"
JAR_FILE = "target/#{ARTIFACT_ID}-#{DXJRuby::VERSION}.jar"

file JAR_FILE => SRC_FILES do
  sh %( ./build.sh make-jar )
end

task :make_jar => JAR_FILE
